---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ kube_resource_name }}-www-data
  namespace: {{ kube_resource_namespace }}
  labels:
    {{ kube_resource_labels | to_nice_yaml(indent=2) | indent(4) }}
data:
  shake.css: |
    @keyframes shake {
      10%, 90% { transform: translate3d(-1px, 0, 0); }
      20%, 80% { transform: translate3d(2px, 0, 0); }
      30%, 50%, 70% { transform: translate3d(-4px, 0, 0); }
      40%, 60% { transform: translate3d(4px, 0, 0); }
    }

    table {
      display: inline-block;
      animation: shake 2.5s infinite;
    }
